server:
  port: 8080
  context-path: /uaa


security:
  oauth2:
    client:
      client-id: my-client
      client-secret: my-client-pass
      scope: openid
      authorized-grant-types: password,authorization_code,refresh_token,implicit,client_credentials
      auto-approve-scopes: true
    authorization:
      check-token-access: isAuthenticated()


logging:
  level:
    org.springframework.security: DEBUG
