server:
  port: 8888

oauth2:
  server:
    url: http://localhost:8080

security:
  oauth2:
    client:
      client-id: my-client
      client-secret: my-client-pass
    resource:
      token-info-uri: ${oauth2.server.url}/uaa/oauth/check_token

logging:
  level:
    org.springframework.security: DEBUG
